# Generated by Django 4.1.3 on 2022-11-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='link',
        ),
        migrations.AddField(
            model_name='link',
            name='tags',
            field=models.ManyToManyField(to='core.tag'),
        ),
    ]
